spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

server:
  error:
    whitelabel:
      enable: false
#    팁: 기본값들
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never


